---
title: XR Youth
email: xryouth@gmail.com
description: The Youth Voice of the Rebellion
baseurl: ''
url: ''
markdown: kramdown
theme: jekyll-rebellion
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-get-json
- jekyll-datapage-generator
sass:
  sass_dir: _sass
jekyll_get_json:
- data: insta
  json: https://profilepageimages.usecue.com/images/xryouth_uk/images.json
collections:
  faqs:
    output: true
page_gen-dirs: false
page_gen:
- data: insta
  template: insta
  name_expr: Date.parse(record["timestamp"]).strftime("%Y-%m-%d")+record["caption"].slice(0..5)
  title_expr: record["caption"].slice(0..50)+"..."
  page_data_prefix: ig
  extension: md
airtable:
  faqs:
    app: appOvsegTEAmboAdW
    table: tblQvpIFXBeC1y6sJ
    view: viwpJfiohAaboMXJv
  posts:
    table: tblJ2kxufJS2qGqFy
    view: viwPOgZdyh85akpF8
    collection: true
  authors:
    table: tbledFP3NE9uuSKzf
    view: viwGfu3dM5Lp6Gwh7
  demands:
    table: tblppwvAzVIfty4kI
    view: viwDCKTvKt7dZROcr
permalink: "/:categories/:title/"
logo_square: "/assets/images/xr-youth-logo.png"
logo: "/assets/images/words-logo-without-bg.png"
logo_light: "/assets/images/xr-youth-logo.png"
facebook: https://www.facebook.com/XRYouth
twitter: https://twitter.com/xryouthuk
instagram: https://www.instagram.com/xryouth_uk/
copyright_notice: Made with love from [Websites for Dissent](https://joe.irving.me.uk).
donate: https://www.chuffed.org/project/xr-youth-uk
join_us: "/join-us/"
brand_color: "$xr-dark-blue"
accent_color: red
invert_brand_text: false
invert_accent_text: true
theme_tiny: "250"
theme_small: "425"
theme_medium: "570"
theme_large: "770"
header_pages: 
exclude:
- README.md
- pages/README.md
- _posts/README.md
