title: XR Youth
email: xryouth@gmail.com
description: >-
  The Youth Voice of the Rebellion against Extinction
baseurl: "https://joe-irving.github.io/xryouth.ga"
url: ""
destination: ./docs

# Build settings
markdown: kramdown
theme: jekyll-rebellion

plugins:
 - jekyll-feed
 - jekyll-seo-tag

sass:
  sass_dir: _sass

permalink: /:title/

# Rebellion Config
# logo: /assets/images/logo.jpeg
logo_square: /assets/images/logo.jpeg
#logo_light: /assets/logo-white.svg
facebook: https://www.facebook.com/XRYouth
twitter: https://twitter.com/NetworkXr
instagram: https://www.instagram.com/xryouth/
# copyright_notice: Add an additional copyright notice here.
donate: /donate/
join_us: /join-us/
# $xr-green, $xr-yellow, $xr-light-blue, $xr-pink, $xr-purple, $xr-dark-blue $xr-light-blue, xr-light-green, $xr-pastel-yellow
brand_color: $xr-yellow
accent_color: $xr-dark-blue
invert_brand_text: false
invert_accent_text: true
theme_tiny: 250
theme_small: 425
theme_medium: 570
theme_large: 770
#main_nav_exclude_layouts: # Array of layout names to exclude from the main nav.
#header_pages: Array of pages (filepaths) to include in header nav
